### PR TITLE
Fix side effect when referencing the same resource in multiple stacks

### PR DESCRIPTION
**Pull request by jormaechea**
Fixes issue #106, by avoiding to mutate objects.

### CODE REVIEW

**Comment by dougmoscrop** [comment]
Nice! And just confirming, the integration test fails if you don't include the deep clone?

**Comment by jormaechea** [comment]
Yes, after updating the `serverless` version and the functions `runtime`, it fails to deploy because of the missing parameter in the nested stack.

**Comment by jormaechea** [comment]
@dougmoscrop Hi! Have you been able to find some time to check on this? Thanks!

**Comment by pmaroli** [comment]
Hi @jormaechea 

I pulled your code because I was having the same problem. My 'LambdasNestedStack' got too big and reached the parameter output limit (60), so I decided to split my lambdas up into different nested stacks.

Just like in your example, my second LambdaNestedStack didn't receive a few parameters.

So after I pulled your code and ran `sls package`, the template included the parameters! I tried to deploy using `sls deploy`, but I got the following error:

`Error: The CloudFormation template is invalid: Template error: instance of Fn::GetAtt references undefined resource MyFunctionLambdaFunction`

Any idea why this might happen? Please let me know if you need additional information.

**Comment by jormaechea** [comment]
@pmaroli can you share a minimal config where I can reproduce this issue? It's kinda difficult 
otherwise..

**Comment by pmaroli** [comment]
@jormaechea 

I was able to reproduce the issue using the code snippet that you posted in issue #106 

`sls package` runs fine, but it fails on deployment. Here's a link to the repo I created based off of your code snippet: https://github.com/pmaroli/serverless-split-stacks-error

I made sure to pull the `serverless-plugin-split-stacks` code from this pull request. I got the following error when trying to deploy

```
Error: The CloudFormation template is invalid: Template format error: Unresolved resource dependencies [MySecondFnLambdaFunction] in the Resources block of the template
```

**Comment by jormaechea** [comment]
Ok, i’ll give it a try as soon as I can

**Comment by dougmoscrop** [comment]
I will get to this today, just gotta dawn some anti-apocalypse gear and venture out to the store first.

**Comment by jormaechea** [comment]
LOL! Been there a couple minutes ago... 7th day in a row at home.. I hope everything gets better soon! Good luck wherever you are guys!

**Pull request merged**
