### PR TITLE
Nested stack per function

### PR DESCRIPTION
**Pull request by medikoo**
On top of #10 and #13. I managed to setup a nested stack per function generic configuration

For the record, it's tested to work with following types of lambda specific resources (as configured directly by Serverless framework).
- `AWS::Lambda::Function`
- `AWS::Lambda::Version`
- `AWS::Lambda::Permission`
- `AWS::Logs::LogGroup`
- `AWS::ApiGateway::Resource`
- `AWS::ApiGateway::Method`
- `AWS::Events::Rule`

I believe it should work with others, but that was not tested.

Any custom resources will automatically land in function nested stack if their logical ids is prefixed with lambda normalized name (it's also convention that Serverless internally follows for resource logical ids)

While currently this plugin plays gently and offers to move only the resources that can be moved across the stacks between deployments, the described here the _stack per function_ setup is not as graceful.
The only way to make it work in existing projects is to _remove_ the mono stack and redeploy nested stacks config with this plugin turned on as a fresh new stack deployment.
It's purely because CloudFormation doesn't support _move_ of resources of certain types among stacks (it crashes with _resource already exists_).

@dougmoscrop let me know what's your strategy towards that. do you think such configuration should be a part of this plugin (?) If so, let me know, I'll be happy to prepare a PR.

### CODE REVIEW

**Comment by medikoo** [comment]
@dougmoscrop I've converted it to PR, and proposed a nested stack per lambda customization that can be included with this package, and optionally used by the users.
This customization works very well for projects I work with, but I'm not 100% certain it covers all type of resources that serverless may generate.

**Comment by ozbillwang** [comment]
@medikoo 

I tested with your PR

```
  "devDependencies": {
    "serverless-plugin-split-stacks": "git://github.com/medikoo/serverless-plugin-split-stacks.git#d7abbed5ee"
  }
```

But when deploy with it, i don't see any differences. 

```
Serverless: [serverless-plugin-split-stacks]: Summary: 84 resources migrated in to 4 nested stacks
Serverless: [serverless-plugin-split-stacks]:    Resources per stack:
Serverless: [serverless-plugin-split-stacks]:    - (root): 122
Serverless: [serverless-plugin-split-stacks]:    - APINestedStack: 23
Serverless: [serverless-plugin-split-stacks]:    - FiltersNestedStack: 1
Serverless: [serverless-plugin-split-stacks]:    - PermissionsNestedStack: 30
Serverless: [serverless-plugin-split-stacks]:    - VersionsNestedStack: 30
Serverless: Uploading CloudFormation file to S3...
```

**Comment by medikoo** [comment]
@ozbillwang it's proposed as an option (doesn't load by default).

Have you required `serverless-plugin-split-stacks/customizations/stack-per-lambda` as indicated in [README.md#nested-stack-per-lambda](https://github.com/medikoo/serverless-plugin-split-stacks/blob/d7abbed5ee1f87507a2e802000d02c9c0555c7d6/README.md#nested-stack-per-lambda)

**Comment by brunocascio** [comment]
any update here?

**Comment by dougmoscrop** [comment]
Merging and supporting this is going to be a huge effort especially from a testing perspective, I don't currently have the time, but, I would encourage people to use this plugin here and report back (basically, be testers!)

npm makes this super simple, you just set your version in package.json to `github:medikoo/serverless-plugin-split-stacks#stack-per-lambda`

**Comment by brunocascio** [comment]
@dougmoscrop Yes I'am trying but I got this error:

`An error occurred: ApiGatewayDeployment1517838066426 - No integration defined for method.`

**Comment by medikoo** [comment]
@brunocascio Error you mention seems to refer to one of the core resources, that definitely should be handled properly. Let us know, how it works after latest merge

**Comment by brunocascio** [comment]
Nope :( I ran with `--verbose` without luck.

```
...
CloudFormation - CREATE_IN_PROGRESS - AWS::ApiGateway::Deployment - ApiGatewayDeployment1517844827991
...
CloudFormation - CREATE_FAILED - AWS::ApiGateway::Deployment - ApiGatewayDeployment1517844827991
...

An error occurred: ApiGatewayDeployment1517844827991 - No integration defined for method.
```

**Comment by medikoo** [comment]
@brunocascio I think it may relate to some other resources not mentioned in this message.

To coin it right I would need to see generated templates in `.serverless` folder for two scenarios, when using this plugin (multiple stacks), and without it (single stack).

I assume you don't have this issue when not using this plugin, or when running it without this _nested stack per function_ option (?)

**Comment by brunocascio** [comment]
I'm using this plugin because I cannot be able to deploy (APINestedStack limits > 60)

Now, I deployed with only 1 function and it works. Let me a minutes to figure out whats happens :)

**Comment by medikoo** [comment]
> Now, I deployed with only 1 function and it works. Let me a minutes to figure out whats happens :)

It might be that some type of resource, which I did not envision needs special handling. Still to confirm on that I would need to see the templates.

Additionally mind that current version of this plugin, doesn't respect configuration changes for stack updates.
So to be sure that you're fully using nested stack propagation per lambda you need to start with fresh stack (either new one, or delete one you want to update). I discussed that behavior with @dougmoscrop here: https://github.com/dougmoscrop/serverless-plugin-split-stacks/commit/b1a32f1c9c200131798f8db8d2d9d176a299d54a#r25986411

**Comment by brunocascio** [comment]
Yes, I've started from scratch.

Some function throw exceptions and I don't understand why.

Example:

```
...
cars:
    handler: api/cars/route.handler
    events:
      - http:
          method: post
          path: me/cars
          cors: true
      - http:
          method: patch
          path: me/cars/{id}
          cors: true

...
```

Cloudformation template generated after error:

```
{
  "AWSTemplateFormatVersion": "2010-09-09",
  "Description": "CarsNestedStack nested stack",
  "Parameters": {
    "IamRoleLambdaExecutionArnParameter": {
      "Type": "String"
    },
    "ServerlessDeploymentBucketParameter": {
      "Type": "String"
    },
    "ApiGatewayRestApiParameter": {
      "Type": "String"
    },
    "ApiGatewayResourceMeParameter": {
      "Type": "String"
    }
  },
  "Resources": {
    "CarsLogGroup": {
      "Type": "AWS::Logs::LogGroup",
      "Properties": {
        "LogGroupName": "/aws/lambda/project-api-qa-cars"
      },
      "DependsOn": []
    },
    "CarsLambdaFunction": {
      "Type": "AWS::Lambda::Function",
      "Properties": {
        "Code": {
          "S3Bucket": {
            "Ref": "ServerlessDeploymentBucketParameter"
          },
          "S3Key": "serverless/project-api/qa/1517867116103-2018-02-05T21:45:16.103Z/cars.zip"
        },
        "FunctionName": "project-api-qa-cars",
        "Handler": "api/cars/route.handler",
        "MemorySize": 128,
        "Role": {
          "Ref": "IamRoleLambdaExecutionArnParameter"
        },
        "Runtime": "nodejs6.10",
        "Timeout": 15,
        "Environment": {
          "Variables": {
            "DB_DEBUG": "true",
            "PG_HOST": "thehost.com",
            "PG_USER": "project",
            "PG_PASSWORD": "thepassword",
            "PG_DATABASE": "thedatabase"
          }
        }
      },
      "DependsOn": [
        "CarsLogGroup"
      ]
    },
    "ApiGatewayResourceMeCars": {
      "Type": "AWS::ApiGateway::Resource",
      "Properties": {
        "ParentId": {
          "Ref": "ApiGatewayResourceMeParameter"
        },
        "PathPart": "cars",
        "RestApiId": {
          "Ref": "ApiGatewayRestApiParameter"
        }
      },
      "DependsOn": []
    },
    "ApiGatewayResourceMeCarsIdVar": {
      "Type": "AWS::ApiGateway::Resource",
      "Properties": {
        "ParentId": {
          "Ref": "ApiGatewayResourceMeCars"
        },
        "PathPart": "{id}",
        "RestApiId": {
          "Ref": "ApiGatewayRestApiParameter"
        }
      },
      "DependsOn": []
    },
    "ApiGatewayMethodMeCarsPost": {
      "Type": "AWS::ApiGateway::Method",
      "Properties": {
        "HttpMethod": "POST",
        "RequestParameters": {},
        "ResourceId": {
          "Ref": "ApiGatewayResourceMeCars"
        },
        "RestApiId": {
          "Ref": "ApiGatewayRestApiParameter"
        },
        "ApiKeyRequired": false,
        "AuthorizationType": "NONE",
        "Integration": {
          "IntegrationHttpMethod": "POST",
          "Type": "AWS_PROXY",
          "Uri": {
            "Fn::Join": [
              "",
              [
                "arn:aws:apigateway:",
                {
                  "Ref": "AWS::Region"
                },
                ":lambda:path/2015-03-31/functions/",
                {
                  "Fn::GetAtt": [
                    "CarsLambdaFunction",
                    "Arn"
                  ]
                },
                "/invocations"
              ]
            ]
          }
        },
        "MethodResponses": []
      },
      "DependsOn": []
    },
    "ApiGatewayMethodMeCarsIdVarPatch": {
      "Type": "AWS::ApiGateway::Method",
      "Properties": {
        "HttpMethod": "PATCH",
        "RequestParameters": {},
        "ResourceId": {
          "Ref": "ApiGatewayResourceMeCarsIdVar"
        },
        "RestApiId": {
          "Ref": "ApiGatewayRestApiParameter"
        },
        "ApiKeyRequired": false,
        "AuthorizationType": "NONE",
        "Integration": {
          "IntegrationHttpMethod": "POST",
          "Type": "AWS_PROXY",
          "Uri": {
            "Fn::Join": [
              "",
              [
                "arn:aws:apigateway:",
                {
                  "Ref": "AWS::Region"
                },
                ":lambda:path/2015-03-31/functions/",
                {
                  "Fn::GetAtt": [
                    "CarsLambdaFunction",
                    "Arn"
                  ]
                },
                "/invocations"
              ]
            ]
          }
        },
        "MethodResponses": []
      },
      "DependsOn": []
    },
    "CarsLambdaPermissionApiGateway": {
      "Type": "AWS::Lambda::Permission",
      "Properties": {
        "FunctionName": {
          "Fn::GetAtt": [
            "CarsLambdaFunction",
            "Arn"
          ]
        },
        "Action": "lambda:InvokeFunction",
        "Principal": "apigateway.amazonaws.com",
        "SourceArn": {
          "Fn::Join": [
            "",
            [
              "arn:aws:execute-api:",
              {
                "Ref": "AWS::Region"
              },
              ":",
              {
                "Ref": "AWS::AccountId"
              },
              ":",
              {
                "Ref": "ApiGatewayRestApiParameter"
              },
              "/*/*"
            ]
          ]
        }
      },
      "DependsOn": []
    }
  },
  "Outputs": {
    "ApiGatewayResourceMeCars": {
      "Value": {
        "Ref": "ApiGatewayResourceMeCars"
      }
    },
    "ApiGatewayResourceMeCarsIdVar": {
      "Value": {
        "Ref": "ApiGatewayResourceMeCarsIdVar"
      }
    }
  }
}
```

**Comment by brunocascio** [comment]
I tried this:

```
cars:
    handler: api/cars/route.handler
    events:
      - http:
          method: post
          path: me/cars
          cors: true
```

Then:

`serverless deploy`. Works

After that:

```
cars:
    handler: api/cars/route.handler
    events:
      - http:
          method: post
          path: me/cars
          cors: true
      - http:
          method: patch
          path: me/cars/{id}
          cors: true
```

`serverless deploy` Works.

I don't know whats happens...

**Comment by brunocascio** [comment]
@medikoo @dougmoscrop 

I removed all `cors: true` lines from my serverless.yml and the API was successfully deployed. But I need cors in order to make requests from the browser.

Thoughts?

**Comment by medikoo** [comment]
@brunocascio I've [coined it](https://github.com/dougmoscrop/serverless-plugin-split-stacks/pull/14/commits/79b4fa5db829dd3663a733a537bd6d174a63dfb9), `AWS::ApiGateway::Method` resource related to `OPTIONS` method was not deducted out of a box (as no event of that method is mentioned in configuration).

I've fixed it, so please check if now that works for you

**Comment by brunocascio** [comment]
@medikoo Works!!! 🎉  Thank you so much!

I'm going to try with your latest changes.

**Comment by brunocascio** [comment]
@medikoo Works like a charm :)

**Comment by dougmoscrop** [comment]
Glad to hear it! I would love to try this with some of our larger services at my work. Just don't have the time right now.

**Comment by brunocascio** [comment]
We are working with the following staks (and growing up).

```
Serverless: [serverless-plugin-split-stacks]: Summary: 248 resources migrated in to 19 nested stacks
Serverless: [serverless-plugin-split-stacks]:    Resources per stack:
Serverless: [serverless-plugin-split-stacks]:    - (root): 26
Serverless: [serverless-plugin-split-stacks]:    - aNestedStack: 9
Serverless: [serverless-plugin-split-stacks]:    - bNestedStack: 9
Serverless: [serverless-plugin-split-stacks]:    - cNestedStack: 15
Serverless: [serverless-plugin-split-stacks]:    - dNestedStack: 21
Serverless: [serverless-plugin-split-stacks]:    - eNestedStack: 9
Serverless: [serverless-plugin-split-stacks]:    - eNestedStack: 24
Serverless: [serverless-plugin-split-stacks]:    - fNestedStack: 15
Serverless: [serverless-plugin-split-stacks]:    - gNestedStack: 9
Serverless: [serverless-plugin-split-stacks]:    - hNestedStack: 8
Serverless: [serverless-plugin-split-stacks]:    - iNestedStack: 27
Serverless: [serverless-plugin-split-stacks]:    - jNestedStack: 14
Serverless: [serverless-plugin-split-stacks]:    - kNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - lNestedStack: 16
Serverless: [serverless-plugin-split-stacks]:    - mnNestedStack: 2
Serverless: [serverless-plugin-split-stacks]:    - nNestedStack: 2
Serverless: [serverless-plugin-split-stacks]:    - oNestedStack: 20
Serverless: [serverless-plugin-split-stacks]:    - pNestedStack: 10
Serverless: [serverless-plugin-split-stacks]:    - qNestedStack: 23
Serverless: [serverless-plugin-split-stacks]:    - rNestedStack: 9
```

With this feature, we mitigate the resource templates limits (< 200) and Nested stacks limits (< 60).

If I have some helpful tips, I will write here.

**Comment by dougmoscrop** [comment]
I will try to put time in to testing this with our stuff this week and report back. Thanks so much for your patience.

**Comment by mataide** [comment]
Hey Boys,

I am using this version to test:    
` "serverless-plugin-split-stacks": "github:medikoo/serverless-plugin-split-stacks#stack-per-lambda"`

But I got this error:
```
 Serverless Error ---------------------------------------

  Serverless plugin "serverless-plugin-split-stacks" initialization errored: Cannot find module 'serverless/lib/plugins/aws/lib/naming'
```

**Comment by mataide** [comment]
The serverless is installed globally, so the required module cant be loaded like this.

One way to solve this is add `npm link serverless` in your installation process.
So it will add a local link to the serverless module.

**Comment by mataide** [comment]
The number of the resources per stack is the same for me before and after.

What I did:

npm install `"serverless-plugin-split-stacks": "github:medikoo/serverless-plugin-split-stacks#stack-per-lambda"`

`require('serverless-plugin-split-stacks/customizations/stack-per-lambda');` inside /lib/stacks-map.js

```
serverless remove
serverless deploy
```

**Comment by mataide** [comment]
I am sure that the file is reading from here:

```
// Load eventual stacks map customizations
    const customizationsPath = path.resolve(serverless.config.servicePath, 'stacks-map.js');
```
But the number of resources is the same.

This configuration is confusing, it should be a config inside serverless.yml just like others plugins. Ex:

```
custom:
  splitstacks:
    perLambda: true
```

**Comment by mataide** [comment]
It is working now, I had `copy require('serverless-plugin-split-stacks/customizations/stack-per-lambda'); inside /lib/stacks-map.js`, its wrong.

My API have +300 resources, if this config fully works, I think that it should be a default configuration in the plugin, as I said:

```
custom:
  splitstacks:
    perLambda: true //default
```

So user just need to setup this config if they dont want to split the stack per lambda.

**Comment by dougmoscrop** [comment]
I agree about the config inside the lambda yml.

My goal would be to make 2.0 default to this behavior. It just needs more
exhaustive testing.

**Comment by mataide** [comment]
I think that you could release a 2.0-rc1, people won´t test it if remain as PR.

**Comment by dougmoscrop** [comment]
I think we can include it in a minor ver disabled by default. Opt in.
Agreed that the PR isn't a good testing bed. I started doing some testing
today and it looks good.

**Comment by medikoo** [comment]
@mataide 

> The serverless is installed globally, so the required module cant be loaded like this.

To match properly resources to given functions, the plugin relies directly on serverless resource name resolvers. Hence why access to `serverless` API is needed.

`serverless` is marked as a _peer_ dependency, so if it is not found, you should at least see clear warning when doing `npm install`.

I believe, it also shouldn't be seen as real issue. In real project is never a good practice to rely purely on global installation. Main reason is you can't ensure expected version range that way (what's globally installed is completely disconnected from local install), additionally depending on global installs makes projects not easily installable in other places.

So I take it's fair to assume that`serverless` is installed locally,  at least as a dev dependency.

> This configuration is confusing, it should be a config inside serverless.yml just like others plugins

I take we have an agreement on that, so I'll add a patch that brings  handling of `perLambda: true` in custom settings

**Comment by medikoo** [comment]
@dougmoscrop I've updated it, so now _per lambda_ mode is invoked by:

```yaml
custom:
  splitStacks:
    mode: 'lambda'
```

Together with it I introduced generic modes organization (so both configurations are in `mode` folder), and updated documentation

---

__Warning: if anyone relied on `medikoo/serverless-plugin-split-stacks#stack-per-lambda` as  dependency, then that change certainly broke things for you. I suggest to pin to specific commit instead (not branch, so e.g. `medikoo/serverless-plugin-split-stacks#2c89584dbe4`), and monitor this PR.__

**Comment by dougmoscrop** [comment]
I'm not sure that perLambda is a mode, because there are other resources, that may still need to be migrated, that aren't for a specific function. I'm going to merge this now and work on a release.

**Comment by medikoo** [comment]
> I'm not sure that perLambda is a mode, because there are other resources, that may still need to be migrated

This mode (at least as proposed) splits resources purely per lambda, with no additional split directives.
What stays in `root` stack seems really minor (at least it in cases I dealt with). So I think name seems quite valid :)

**Comment by dougmoscrop** [comment]
The resource-to-lambda-function logic is flawed... 

If someone calls their function "api", it will match all the Api* resources (ApiGatewayRestApi, etc). I noticed this by accident when running the integration tests, which simply have functions called "A" and "B", so the ApiGatewayRestApi gets migrated in to the "A" stack.

It means that any functions that happen to have a name that is a prefix for a resource will get misattributed. How likely this is, I don't know - I do know people call their function "api" when they are running a single HTTP handler for all things.

My initial implementation tried to be a lot more specific - each resource type had an implementation of "getAssociatedFunction()" which would return only if there was one, and only one, function for a given resource. Multiple functions would never be considered the same.

I have similar concerns about the way API resources are migrated -- it only looks at the point-of-deploy count of `<= 1` associated functions to a given resource. But if a user changes their Serverless configuration, they can get in to a state where the migrated resource is stuck living on a stack related to only one of the associated functions...

**Comment by dougmoscrop** [comment]
I think the API stuff should just go in to a separate API stack.

We have to also accept that there are going to be practical limits here: you won't be able to have more than 58 functions on a given deployment, since there's at least two other outputs added (API gateway endpoint and S3 bucket). Unless we use Map<> in the outputs (!)

As long as we can move at least one other resource than the Lambda Function itself with the function to a function stack, it's a net-win. And there is: the Version. There's also `AWS::Lambda::Permission` which points directly at a specific function, so I wonder if we can go to a hybrid mode where every function goes in to it's own stack, and then come up with candidates that we know for sure can safely go to the stack with the function.

**Comment by dougmoscrop** [comment]
@medikoo I pushed my changes to how I was thinking about the perType/perLambda, please take a peek and consider working from there so we don't have merge conflicts.

**Comment by medikoo** [comment]
>The resource-to-lambda-function logic is flawed... The resource-to-lambda-function logic is flawed... If someone calls their function "api", it will match all the Api* resources (ApiGatewayRestApi, etc). 

Yes, really generic lambda names may by accident match common resources. I indeed overlooked that. Still that's quite easy to patch, with some black list handling at: https://github.com/medikoo/serverless-plugin-split-stacks/blob/stack-per-lambda/modes/lambda.js#L75

_I really wouldn't say, it makes whole logic "flawed" ;-)_

> Multiple functions would never be considered the same.

This is the idea behind what I proposed. If resource is used by more than one lambda it stays in root stack, that's the goal.

> But if a user changes their Serverless configuration, they can get in to a state where the migrated resource is stuck living on a stack related to only one of the associated functions...

Yes and I already indicated in other discussion, I'm not happy that this plugin does it (forces resource to stick to stack in which it once landed). It would be way better to have a way to opt out from it.
(for sure plugin should issue logs about such events).

e.g. in my use case it's totally not desirable. If such changes occur (resource is supposed to be moved across stacks), it's always result of some major refactor and reset of stacks is way more preferable than sticking to more and more chaotic distribution across nested stacks.

> I think the API stuff should just go in to a separate API stack.

This wouldn't work well for my case, where majority of my stack is API resources, and with that approach the outcome resolution will no longer be really _per lambda_ approach which it feels way more logical in my case. Additionally I observe significantly faster deployments with larger number of stacks (per lambda approach) which are deployed in parallel, instead of few large ones that try to maximize resources per stack usage (per type approach).

Anyway if you keep the plugin open for external customization as it's in currently published version so I'll be able to stick to version I already use, then there's not problem for me if you go that way.

> We have to also accept that there are going to be practical limits here: you won't be able to have more than 58 functions on a given deployment,

Definitely, and if someone deals with that scenario, then I believe should stick to resource type resolution or even more likely to come up with customization specific it his extreme use case.

> @medikoo I pushed my changes to how I was thinking about the perType/perLambda, please take a peek and consider working from there so we don't have merge conflicts.

I spotted few issues and commented on those. What's most important, that breaking change is introduced (customizations are no longer accepted as in currently published version). If you decide to publish it in same version range it will break project I work with, therefore please don't do that :)

**Comment by dougmoscrop** [comment]
Sorry, by flawed I only meant, didn't work perfectly :)

So my concern is any migration that would change.  I think the built-in function migration needs to be conservative, and only migrate resources that can *ever* be associated to a single function. Yes, if you want to do it more aggressively -- by all means.

I did not intend to, nor do I expect I have, broken external customization, but I do plan on changing it for 2.0 -- I will respond to your comments.

**Comment by dfloresgonz** [comment]
@brunocascio 
What feature are you using? I'm getting this error: The CloudFormation template is invalid: Template format error: Outputs count 78 is greater than max allowed 60

> With this feature, we mitigate the resource templates limits (< 200) and Nested stacks limits (< 60).

**Comment by dougmoscrop** [comment]
What are the outputs? 

Your service is too big for the current state of this plugin.  We can try to use Map parameters (PR welcome) to move the limit upward.  Smaller things are still always better than bigger.

**Comment by dfloresgonz** [comment]
Hi @dougmoscrop I got this:

`$ sls deploy
Serverless: Packaging service...
Serverless: Excluding development dependencies...
Serverless: [serverless-plugin-split-stacks]: Summary: 417 resources migrated in to 77 nested stacks
Serverless: [serverless-plugin-split-stacks]:    Resources per stack:
Serverless: [serverless-plugin-split-stacks]:    - (root): 80
Serverless: [serverless-plugin-split-stacks]:    - APINestedStack: 5
Serverless: [serverless-plugin-split-stacks]:    - ActualizarPagosNestedStack: 3
Serverless: [serverless-plugin-split-stacks]:    - AppNestedStack: 7
Serverless: [serverless-plugin-split-stacks]:    - ChangeRolByPersonaNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - ConfigDescuentoSedeNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - CrearCorreosMasivosRuleEnviosNestedStack: 3
Serverless: [serverless-plugin-split-stacks]:    - CrearCuentasGSuiteColaboradoresNestedStack: 3
Serverless: [serverless-plugin-split-stacks]:    - CrearCuentasGSuiteEstudiantesNestedStack: 3
Serverless: [serverless-plugin-split-stacks]:    - CrearRuleEnvioCorreoMasivoTesoNestedStack: 3
Serverless: [serverless-plugin-split-stacks]:    - CrearRuleMailDesfasadoNestedStack: 3
Serverless: [serverless-plugin-split-stacks]:    - DeleteCapacitacionNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - DeleteEstudioNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - DeleteFilesFromPapeleraNestedStack: 3
Serverless: [serverless-plugin-split-stacks]:    - DeleteHistorialMedicoNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - DownloadCredentialsNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - EditCampoProfNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - EditFichaMedicaNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - EditarCapacitacionNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - EditarContratoNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - EditarStudyByColaboradorNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - EliminarAdelantoNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - EnviarCorreosMasivosNestedStack: 3
Serverless: [serverless-plugin-split-stacks]:    - EnviarReporteDiarioCajasNestedStack: 3
Serverless: [serverless-plugin-split-stacks]:    - EnvioSaludosCumpleanosNestedStack: 3
Serverless: [serverless-plugin-split-stacks]:    - GenerarCompromisosMasivosNestedStack: 3
Serverless: [serverless-plugin-split-stacks]:    - GetAreasEspecificasNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - GetCollaboratorsFilterNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - GetComboCapacitacionNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - GetCombosContratoNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - GetCombosCreateStudyNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - GetCombosHistoryMedicalNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - GetConfigAdelantoSedeNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - GetContratoActivoNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - GetContratoByPersonaNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - GetDataCapacitacionesNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - GetDataCollaboratorContratoNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - GetDataCollaboratorbyIdNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - GetDataComplemetariaNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - GetDataDomicilioNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - GetDataEstudiosNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - GetDataNacimientoNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - GetDatosConfiguracionNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - GetDatosProfesionalNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - GetDatosRescindirNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - GetFilterEstadoNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - GetHistoryAdelantoNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - GetHistorySalaryAdvanceNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - GetInfoMedicaNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - GetListPersAccessNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - GetListPersbyNotifNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - GetListRolesByPersonaNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - GetNivelesNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - GetPermisosByUserNestedStack: 8
Serverless: [serverless-plugin-split-stacks]:    - GetSedebyEmpresaNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - GetcombosRegisNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - InsertCollaboratorNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - MigrarClassroomNestedStack: 3
Serverless: [serverless-plugin-split-stacks]:    - PagarDescuentoPlanillaNestedStack: 3
Serverless: [serverless-plugin-split-stacks]:    - RegisterStudyByColaboradorNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - RegistrarAdelantoNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - RegistrarCapacitacionNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - RegistrarConfigAdelantoNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - RegistrarContratoNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - RegistrarHistorialMedicoNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - RenovarContratoNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - RescindirContratoByPersonaNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - SendCredentialsNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - SendEmailNestedStack: 3
Serverless: [serverless-plugin-split-stacks]:    - SendPushToTopicNestedStack: 3
Serverless: [serverless-plugin-split-stacks]:    - SetConfigNotificationNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - SetPeopleNotificationNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - SuspenderCuentasGSuiteEstudiantesNestedStack: 3
Serverless: [serverless-plugin-split-stacks]:    - UpdateCondicionSedeNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - UpdateHistorialMedicoNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - UpdateProgramaNestedStack: 6
Serverless: [serverless-plugin-split-stacks]:    - ValidateTokenNestedStack: 7
Serverless: [serverless-plugin-split-stacks]:    - VerificarAdelantoEspecialNestedStack: 6
Serverless: Creating Stack...
Serverless: Checking Stack create progress...
.....
Serverless: Stack create finished...
Serverless: Uploading CloudFormation file to S3...
Serverless: Uploading artifacts...
Serverless: Uploading service .zip file to S3 (36.79 MB)...
Serverless: Validating template...

  Error --------------------------------------------------

  The CloudFormation template is invalid: Template format error: Outputs count 78 is greater than max allowed 60

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Get Support --------------------------------------------
     Docs:          docs.serverless.com
     Bugs:          github.com/serverless/serverless/issues
     Forums:        forum.serverless.com
     Chat:          gitter.im/serverless/serverless

  Your Environment Information -----------------------------
     OS:                     win32
     Node Version:           8.9.4
     Serverless Version:     1.26.1`

**Pull request merged**
