### PR TITLE
check to named config does not exist

### PR DESCRIPTION
**Pull request by haruharuharuby**
#16 This is the cause of access to bucket element which does not exist.
So I use hasOwnProperty() method to check named config exists or not.

### CODE REVIEW

**Comment by dougmoscrop** [comment]
hmm I don't think this changes the behavior at all, your test will still pass with the same ol' falsey-check code.  

the bug in 1.4.0 was caused by me making a typo: https://github.com/dougmoscrop/serverless-plugin-split-stacks/commit/43522a5034b1f1c12992f69cd0c89028bf590317#diff-182cc54c5fac736e9a5c73e3c002bd3cL91 (deploymentBucket vs. deploymentBuckeetObject)

**Comment by haruharuharuby** [comment]
Sorry, My explanation does not enough.

I encounter this error when I was deploying code.

`
Serverless: Uploading service .zip file to S3 (11.54 MB)...

  Type Error ---------------------------------------------

  Cannot read property 'serverSideEncryption' of undefined

     For debugging logs, run again after setting the "SLS_DEBUG=*" environment variable.

  Stack Trace --------------------------------------------

TypeError: Cannot read property 'serverSideEncryption' of undefined
    at encryptionFields.reduce (/Users/tomoharuitoh/tinms/xxxxxxx/tinms-api/node_modules/serverless-plugin-split-stacks/lib/utils.js:289:33)
    at Array.reduce (native)
    at ServerlessPluginSplitStacks.getEncryptionParams (/Users/tomoharuitoh/tinms/xxxxxxx/tinms-api/node_modules/serverless-plugin-split-stacks/lib/utils.js:288:29)
    at Promise.all._.map.file (/Users/tomoharuitoh/tinms/xxxxxxx/tinms-api/node_modules/serverless-plugin-split-stacks/split-stacks.js:92:43)
    at arrayMap (/Users/tomoharuitoh/tinms/xxxxxxx/tinms-api/node_modules/lodash/lodash.js:631:23)
    at Function.map (/Users/tomoharuitoh/tinms/xxxxxxx/tinms-api/node_modules/lodash/lodash.js:9546:14)
    at provider.getServerlessDeploymentBucketName.then.deploymentBucket (/Users/tomoharuitoh/tinms/xxxxxxx/tinms-api/node_modules/serverless-plugin-split-stacks/split-stacks.js:83:30)
From previous event:
    at ServerlessPluginSplitStacks.upload (/Users/tomoharuitoh/tinms/xxxxxxx/tinms-api/node_modules/serverless-plugin-split-stacks/split-stacks.js:80:8)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:360:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:360:22)
    at PluginManager.spawn (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:378:17)
    at AwsDeploy.BbPromise.bind.then (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:91:48)
From previous event:
    at Object.deploy:deploy [as hook] (/usr/local/lib/node_modules/serverless/lib/plugins/aws/deploy/index.js:87:10)
    at BbPromise.reduce (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:360:55)
From previous event:
    at PluginManager.invoke (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:360:22)
    at PluginManager.run (/usr/local/lib/node_modules/serverless/lib/classes/PluginManager.js:391:17)
    at variables.populateService.then (/usr/local/lib/node_modules/serverless/lib/Serverless.js:99:33)
    at runCallback (timers.js:672:20)
    at tryOnImmediate (timers.js:645:5)
    at processImmediate [as _immediateCallback] (timers.js:617:5)
From previous event:
    at Serverless.run (/usr/local/lib/node_modules/serverless/lib/Serverless.js:86:74)
    at serverless.init.then (/usr/local/lib/node_modules/serverless/bin/serverless:39:50)
`

The cause of this error is deployment bucket in serverless.yml and 
https://github.com/haruharuharuby/serverless-plugin-split-stacks/blob/master/lib/utils.js#L289
`

**serverless.yml**
:
provider:
  :
  deploymentBucket: serverless.${self:provider.region}.deploys
:
`

This error is fixed by modifying serverless.yml
:
provider:
  :
  deploymentBucket: 
    name: serverless.${self:provider.region}.deploys
    serverSideEncryption: AES256
:
`

if serverSideEncryption does not specified in serverless.yml, getEncryptionParams() method try to 
access no existing element. then error occurred.

So I thought if it does not specify serverSideEncryption,  it is better to not add to memo variable.

... and I found issue #16, I thought this issue is similar to above error.

My environment
     Node Version:           6.10.3
     Serverless Version:     1.23.0
     plugin-version: 1.4.0

Thanks

**Comment by dougmoscrop** [comment]
Yes, this issue was fixed in 1.4.1

**Comment by haruharuharuby** [comment]
Thank you. I confirmed this issue by 1.4.1.

**Comment by dougmoscrop** [comment]
Oh sorry are you saying it still happens?

**Comment by haruharuharuby** [comment]
Sorry, too.
This means I confirmed that this issue was fixed :)

**Pull request closed without merging**
