### PR TITLE
Splits on resource references

### PR DESCRIPTION
**Pull request by vicary**
I am not sure but if all that split-stacks do for parameters are resource references, this should completely solves the problem of #123. Even if not, it should greatly improves the situation.

### CODE REVIEW

**Comment by dougmoscrop** [comment]
Yeah I just can't remember if this is before or after resolving same-stack references.  Like we don't want to count them as parameters if they in fact go in to the same stack. have you tested this by any chance?

**Comment by vicary** [comment]
Tracing with my best efforts,

1. `replaceReferences()` https://github.com/dougmoscrop/serverless-plugin-split-stacks/blob/471ce54f49815cafdd1c3a4f442122338675313f/split-stacks.js#L60-L70
2. `reconcile()` and `parameterize()` https://github.com/dougmoscrop/serverless-plugin-split-stacks/blob/471ce54f49815cafdd1c3a4f442122338675313f/lib/replace-references.js#L16-L42
3. Only by the time `reconcile()` runs we know for sure if it is a parameter or not https://github.com/dougmoscrop/serverless-plugin-split-stacks/blob/471ce54f49815cafdd1c3a4f442122338675313f/lib/utils.js#L291-L306
4. `stackHasRoom()` <- `getStackName()` is invoked by both `migrateExistingResources()` and `migrateNewResources()`, which ran before `replaceReferences()`.

Because it is still in the middle of adding resources into the stacks, we don't have enough information to infer a meaningful answer for the question *Is the stack still has room?* even if we keep an internal object reference inside `stackHasRoom()`.

It is logically a circular dependency, but does it make sense to recursively and incrementally resolve this?

1. Migrations
2. Parameterize regardless of limits
3. Add a new check, such that if stack limit is exceed, go back to step 1.

Or am I understanding the issue correctly?

**Comment by dougmoscrop** [comment]
That sounds vaguely familiar as why I didn't implement the parameter splitting to begin with!

**Comment by vicary** [comment]
Hm... how shall we move this forward?

Implementing a recursive resolution would means, instead of simple allocation, the code should also know how to move allocated resources around before deployment, sounds quite some refactoring to be done TBH.

So do you think it's a correct direction, and do you feel comfortable with this level of refactoring?

**Comment by dougmoscrop** [comment]
I'm wondering if we should just pause, and see how much of a problem it is with the new CFn limits.  Pushing those, means someone is creating a really really huge project.

What do you think?

**Comment by vicary** [comment]
Oh, thanks for the heads up! The new limits are actually exciting!

But at the same time I am not sure what classifies as huge. My project has 300 lambdas and is still growing, and I honestly believe any decent sized commercial project would easily exceed 500 resources.

**Comment by dougmoscrop** [comment]
I strongly encourage you to try to find ways to break that application up in to sub-applications.  Deployments with CloudFormation are not atomic anyway, it can create a false sense of uniformity or consistency or blue-green safety within the application, you know? And you will come to regret the downtime when your CloudFormation stack gets in to a bad state (UPDATE_ROLLBACK_FAILED) and you may have to remove and redeploy the entire thing at the behest of AWS support!

**Comment by dougmoscrop** [comment]
Oh, and you may be interested in my other plugin, `serverless-plugin-bootstrap`, which is for moving resources that persist state outside of the application 'tier' to make it easier to safely remove+redeploy in a panic.

It supports some primitive diffs, so when you do `sls deploy` it will actually detect that, for example, a dynamo table has changed, or an sqs queue does not exist  - similar but of course not nearly as robust as terraform.  It supports packaging nested stacks similar to how the awscli does (in that it will upload nested stack templates to S3 first, then substitute their references in the bootstrap stack) - so what you gain from that is many more resources you can deploy, output and/or export and reference in your application (`${cf:stack-name-output-name}`) that are not touched as part of your normal deployment (other than confirming that your local IaC matches your cloud infrastructure).  It is ideal for things that do not change often and are persistent (queues, streams, s3 buckets, etc).

**Comment by vicary** [comment]
My project is just one single AppSync application, all those lambdas are just tiny resolvers (<50kb each). Databases and other parts of the system is already spun off into standalone stacks.

I can wait for https://github.com/serverless-components/graphql to mature and refactor the whole project into serverless components, the output reference looks interesting and that may save us from inventing a new way of getting ARNs from resolving multiple standalone lambda stacks into the AppSync stack.

But then there are still API rate limits (see [DependsOn Plugin](https://www.serverless.com/plugins/serverless-dependson-plugin)) that neither CF nor sls-component support auto-throttling during deployment.

I know it's quite a lot of marginally related issues here and honestly I think it's CF's responsibility to throttle itself in the deployment process and workaround account limits.

**Comment by vicary** [comment]
Since I have not encountered these limits ever since this fix in my fork, and considered that these limits may change with AWS's internal policies, do you think it's a good idea that we settle this PR by exposing these 3 numbers in `serverless.yml`, having the current numbers in this PR as defaults?

**Comment by dougmoscrop** [comment]
Sounds good!

**Comment by vicary** [comment]
Exposed the configurations, see if you're comfortable with the naming?

**Comment by dougmoscrop** [comment]
Yes looks good, if you could rebase/fix conflicts, I think it's good to go

**Comment by vicary** [comment]
I rebased from master but GitHub said it still has conflicts, resolved it again via web UI. See if that works?

**Comment by dougmoscrop** [comment]
Squash and merge worked

**Comment by vicary** [comment]
@dougmoscrop I guess the rebase must have done funny things to the git log, your squash merge is not picking up my updates on `README.md` at https://github.com/dougmoscrop/serverless-plugin-split-stacks/commit/3dfe607753f56319107693070c137eb1ad8000ab#diff-b335630551682c19a781afebcf4d07bf978fb1f8ac04c6bf87428ed5106870f5

**Pull request merged**
