### PR TITLE
Fix parameters that are used in multiple nested stacks

### LINKED ISSUE #106: Support Serverless >=1.60.2
There was a change introduced in Serverless 1.60.2 that is causing issues with this plugin. See [this issue](https://github.com/serverless/serverless/issues/7206) on the Serverless project.

I'd love to help but have no idea where to start. [This comment](https://github.com/serverless/serverless/issues/7206#issuecomment-575569367) seems to outline the issue.

### PR DESCRIPTION
**Pull request by jormaechea**
Improved previous solution to fix #106 

Now parameters are created and used properly, tested with the error demonstration posted in that issue, and hopefully it works for all cases!

### CODE REVIEW

**Comment by dougmoscrop** [comment]
Thanks! Can you make a test that guards against a regression based on the error in #106?

**Comment by jormaechea** [comment]
I tested the PR a bit further with some other cases and I can confirm it does not work properly.

**It’s not ready to merge**

I'll keep looking into it a bit more when I find some free time..

**Comment by jaikdean** [comment]
Is there anything we can help with on this?

**Comment by jormaechea** [comment]
I couldn't find the right solution to this. You could try yourself @jaikdean..
The problem is when the same parameter is used in multiple nested stacks.

I couldn't find a solution that works for both things at the same time:
- VPC global configuration in `provider` section, used in multiple nested stacks
- Some output from a nested stack that's used in another 2 nested stacks

The `deeplClone` approach work for some but broke others. This PR has the same issues.

**Comment by vicary** [comment]
Tested this one after a master rebase, still got the error `Error: The CloudFormation template is invalid: Template error: instance of Fn::GetAtt references undefined resource LambdaFunction`, should be related to this one https://github.com/dougmoscrop/serverless-plugin-split-stacks/issues/106#issuecomment-603282234.

**Comment by jormaechea** [comment]
I'm closing this PR to prevent merging broken code.. Hope someone comes up with a better approach..

**Pull request closed without merging**
